export const REGISTER_START = 'REGISTER_START';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const ADD_PUBLICATION_SUCCESS = 'ADD_PUBLICATION_SUCCESS';
export const ADD_PUBLICATION_ERROR = 'ADD_PUBLICATION_ERROR';
export const LOAD_PUBLICATIONS_SUCCESS = 'LOAD_PUBLICATIONS_SUCCESS';
export const LOAD_PUBLICATIONS_ERROR = 'LOAD_PUBLICATIONS_ERROR';